

export const UPDATE_VIEWPORT = "UPDATE_VIEWPORT"
export const UPDATE_LISTING = "UPDATE_LISTING"
export const RESET_LISTING = "RESET_LISTING"
export const RESET_VIEWPORT = "RESET_VIEWPORT"
export const UPDATE_ACTIVE = "UPDATE_ACTIVE"
export const SET_DATA = "SET_DATA"
export const SET_DIALYSIS_DATA = "SET_DIALYSIS_DATA"
export const SET_COUNTY = "SET_COUNTY"
export const SET_KING = "SET_KING"
export const SET_SNOHOMISH = "SET_SNOHOMISH"
export const SET_PIERCE = "SET_PIERCE"
export const SET_CANCER_DATA = "SET_CANCER_DATA"
export const SET_LISTING = "SET_LISTING"
export const SET_DIALYSIS_LISTING = "SET_DIALYSIS_LISTING"
export const SET_CANCER_LISTING = "SET_CANCER_LISTING"
export const SET_DIALYSIS_COUNTY = "SET_DIALYSIS_COUNTY"
export const SET_CANCER_COUNTY = "SET_CANCER_COUNTY"
export const RESET_DIALYSIS_LISTING = "RESET_DIALYSIS_LISTING"
export const RESET_CANCER_LISTING = "RESET_CANCER_LISTING"
export const UNMOUNT_DIALYSIS = "UNMOUNT_DIALYSIS"
export const UNMOUNT_CANCER = "UNMOUNT_CANCER"



