

export const UPDATE_VIEWPORT = "UPDATE_VIEWPORT"
export const UPDATE_LISTING = "UPDATE_LISTING"
export const RESET_LISTING = "RESET_LISTING"
export const RESET_VIEWPORT = "RESET_VIEWPORT"
export const UPDATE_ACTIVE = "UPDATE_ACTIVE"
export const SET_DATA = "SET_DATA"
export const SET_DIALYSIS_DATA = "SET_DIALYSIS_DATA"
export const SET_COUNTY = "SET_COUNTY"
export const SET_KING = "SET_KING"
export const SET_SNOHOMISH = "SET_SNOHOMISH"
export const SET_PIERCE = "SET_PIERCE"


